create table if not exists story_photos (
  id bigint generated by default as identity primary key,
  floor integer not null,
  object_id text not null,
  title text not null,
  description text,
  original_path text,
  detail_path text,
  thumb_path text,
  sort_order integer default 0,
  created_at timestamp with time zone default now()
);

insert into story_photos (
  floor,
  object_id,
  title,
  description,
  original_path,
  detail_path,
  thumb_path,
  sort_order
) values
  (1, 'story-object-0', '1번째 오브젝트', '테스트 사진입니다.', 'original/wedding_1.jpg', 'detail/wedding_1.jpg', 'thumb/wedding_1.jpg', 1),
  (2, 'story-object-1', '2번째 오브젝트', '테스트 사진입니다.', 'original/wedding_2.jpg', 'detail/wedding_2.jpg', 'thumb/wedding_2.jpg', 2),
  (3, 'story-object-2', '3번째 오브젝트', '테스트 사진입니다.', 'original/wedding_3.jpg', 'detail/wedding_3.jpg', 'thumb/wedding_3.jpg', 3),
  (4, 'story-object-3', '4번째 오브젝트', '테스트 사진입니다.', 'original/wedding_4.jpg', 'detail/wedding_4.jpg', 'thumb/wedding_4.jpg', 4),
  (5, 'story-object-4', '5번째 오브젝트', '테스트 사진입니다.', 'original/wedding_5.jpg', 'detail/wedding_5.jpg', 'thumb/wedding_5.jpg', 5);
